apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Namespace }}-api-service
    namespace: {{ .Release.Namespace }}
spec:
    selector:
        app: {{ .Release.Namespace }}-api
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    type: ClusterIP
